[package]
name = "bp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tempfile = "3.8"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
chrono = "0.4"
lazy_static = "1.4"
criterion = "0.5"

[features]
log_trace = []
log_debug = []
log_info = []
log_warn = []
log_error = []

[release]
lto = true
panic = "abort"
codegen-units = 1

[[bench]]
name = "random_insert"
harness = false